package dawns.twilight.dao.model;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public_random
 *
 * @mbg.generated do_not_delete_during_merge Thu Feb 28 20:26:08 CST 2019
 */
@Data
public class PublicRandom implements Serializable {
    /**
     * public_random id
     */
    private Integer id;

    /**
     * sequence of game　in progress
     */
    private String gamingSeq;

    /**
     * game round number
     */
    private String gamingRound;

    /**
     * 
     */
    private String publicInput;

    /**
     * 
     */
    private Date createtime;

    /**
     * public_random
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_random
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", gamingSeq=").append(gamingSeq);
        sb.append(", gamingRound=").append(gamingRound);
        sb.append(", publicInput=").append(publicInput);
        sb.append(", createtime=").append(createtime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_random
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PublicRandom other = (PublicRandom) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getGamingSeq() == null ? other.getGamingSeq() == null : this.getGamingSeq().equals(other.getGamingSeq()))
            && (this.getGamingRound() == null ? other.getGamingRound() == null : this.getGamingRound().equals(other.getGamingRound()))
            && (this.getPublicInput() == null ? other.getPublicInput() == null : this.getPublicInput().equals(other.getPublicInput()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_random
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGamingSeq() == null) ? 0 : getGamingSeq().hashCode());
        result = prime * result + ((getGamingRound() == null) ? 0 : getGamingRound().hashCode());
        result = prime * result + ((getPublicInput() == null) ? 0 : getPublicInput().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        return result;
    }
}