package dawns.twilight.dao.mapper;

import dawns.twilight.dao.model.Game;
import dawns.twilight.dao.model.GameExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;;

@Mapper
@Repository
public interface GameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    long countByExample(GameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int deleteByExample(GameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int insert(Game record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int insertSelective(Game record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    List<Game> selectByExample(GameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    Game selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") Game record, @Param("example") GameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByExample(@Param("record") Game record, @Param("example") GameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByPrimaryKeySelective(Game record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByPrimaryKey(Game record);
}