package dawns.twilight.dao.mapper;

import dawns.twilight.dao.model.Gaming;
import dawns.twilight.dao.model.GamingExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;;

@Mapper
@Repository
public interface GamingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaming
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    long countByExample(GamingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaming
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int deleteByExample(GamingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaming
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaming
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int insert(Gaming record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaming
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int insertSelective(Gaming record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaming
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    List<Gaming> selectByExample(GamingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaming
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    Gaming selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaming
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") Gaming record, @Param("example") GamingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaming
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByExample(@Param("record") Gaming record, @Param("example") GamingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaming
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByPrimaryKeySelective(Gaming record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaming
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByPrimaryKey(Gaming record);
}