package dawns.twilight.dao.mapper;

import dawns.twilight.dao.model.LoginUser;
import dawns.twilight.dao.model.LoginUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;;

@Mapper
@Repository
public interface LoginUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    long countByExample(LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int deleteByExample(LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int insert(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int insertSelective(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    List<LoginUser> selectByExample(LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    LoginUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") LoginUser record, @Param("example") LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByExample(@Param("record") LoginUser record, @Param("example") LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByPrimaryKeySelective(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByPrimaryKey(LoginUser record);
}