package dawns.twilight.dao.mapper;

import dawns.twilight.dao.model.PublicRandom;
import dawns.twilight.dao.model.PublicRandomExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;;

@Mapper
@Repository
public interface PublicRandomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_random
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    long countByExample(PublicRandomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_random
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int deleteByExample(PublicRandomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_random
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_random
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int insert(PublicRandom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_random
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int insertSelective(PublicRandom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_random
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    List<PublicRandom> selectByExample(PublicRandomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_random
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    PublicRandom selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_random
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") PublicRandom record, @Param("example") PublicRandomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_random
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByExample(@Param("record") PublicRandom record, @Param("example") PublicRandomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_random
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByPrimaryKeySelective(PublicRandom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_random
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByPrimaryKey(PublicRandom record);
}