package dawns.twilight.dao.mapper;

import dawns.twilight.dao.model.Quotation;
import dawns.twilight.dao.model.QuotationExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;;

@Mapper
@Repository
public interface QuotationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    long countByExample(QuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int deleteByExample(QuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int insert(Quotation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int insertSelective(Quotation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    List<Quotation> selectByExample(QuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    Quotation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") Quotation record, @Param("example") QuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByExample(@Param("record") Quotation record, @Param("example") QuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByPrimaryKeySelective(Quotation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByPrimaryKey(Quotation record);
}