package dawns.twilight.dao.mapper;

import dawns.twilight.dao.model.TexasPoker;
import dawns.twilight.dao.model.TexasPokerExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;;

@Mapper
@Repository
public interface TexasPokerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table texas_poker
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    long countByExample(TexasPokerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table texas_poker
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int deleteByExample(TexasPokerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table texas_poker
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table texas_poker
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int insert(TexasPoker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table texas_poker
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int insertSelective(TexasPoker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table texas_poker
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    List<TexasPoker> selectByExample(TexasPokerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table texas_poker
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    TexasPoker selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table texas_poker
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") TexasPoker record, @Param("example") TexasPokerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table texas_poker
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByExample(@Param("record") TexasPoker record, @Param("example") TexasPokerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table texas_poker
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByPrimaryKeySelective(TexasPoker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table texas_poker
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByPrimaryKey(TexasPoker record);
}