package dawns.twilight.dao.mapper;

import dawns.twilight.dao.model.WalletAddress;
import dawns.twilight.dao.model.WalletAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;;

@Mapper
@Repository
public interface WalletAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_address
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    long countByExample(WalletAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_address
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int deleteByExample(WalletAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_address
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_address
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int insert(WalletAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_address
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int insertSelective(WalletAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_address
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    List<WalletAddress> selectByExample(WalletAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_address
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    WalletAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_address
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") WalletAddress record, @Param("example") WalletAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_address
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByExample(@Param("record") WalletAddress record, @Param("example") WalletAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_address
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByPrimaryKeySelective(WalletAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_address
     *
     * @mbg.generated Thu Feb 28 20:26:08 CST 2019
     */
    int updateByPrimaryKey(WalletAddress record);
}